### ISSUE TITLE
Error with "'" syntax

### ISSUE THREAD

**Issue by glodepa** [turkraft/spring-filter#194]
Hi @torshid,
I have a problem with this rest api example:
**[http://localhost:8080/schedaSempl?q=identificazione.collezione:'D'arco']**
the error is in the input text using **apex**. 
Console error:
**com.turkraft.springfilter.exception.OutOfInputException: Reached end of input before end of text
at com.turkraft.springfilter.compiler.token.input.TextMatcher.match(TextMatcher.java:33)
at com.turkraft.springfilter.compiler.token.input.TextMatcher.match(TextMatcher.java:9)
at com.turkraft.springfilter.compiler.Tokenizer.tokenize(Tokenizer.java:45)
at com.turkraft.springfilter.compiler.Parser.parse(Parser.java:31)
at com.turkraft.springfilter.SpringFilterUtils.getFilterFromInputs(SpringFilterUtils.java:43)
at com.turkraft.springfilter.boot.SpecificationFilterArgumentResolver.getSpecification(SpecificationFilterArgumentResolver.java:44)
at com.turkraft.springfilter.boot.SpecificationFilterArgumentResolver.resolveArgument(SpecificationFilterArgumentResolver.java:37)
at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)**

Can you help me, please?

**Comment by torshid** [comment]
Hello,
It's because you have a quote `'` in your input, you need to escape it using a backslash `\`. You may need to encode it.

**Comment by torshid** [comment]
@glodepa The backslash should solve your problem I think. If not, you can always reopen the issue.
