### ISSUE TITLE
regression on version 2.1.0

### ISSUE THREAD

**Issue by marcopag90** [turkraft/spring-filter#220]
Hello, long time no see 👯!
So, I've just upgraded the library to the latest version, but it seems there's a regression due to this commit: https://github.com/turkraft/spring-filter/commit/5117fec2cdf6af1d7a0135bcc6836fddf495d280#diff-e5984ad41ce0a8624b70f0a28079f35ab37392bfe1fa7b986d813728826eb714

The configuration has changed from a plain Java Configuration to a Spring-like using beans injected in the context here: 
```
@Autowired(required = false)
SpecificationFilterArgumentResolver specificationFilterArgumentResolver;

@Autowired(required = false)
BsonFilterArgumentResolver bsonFilterArgumentResolver;

@Override
public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers) {

    if (FilterUtils.isSpecificationDependencyPresent()) {
      argumentResolvers.add(specificationFilterArgumentResolver);
    }

    if (FilterUtils.isSpringDataMongoDbDependencyPresent()) {
      argumentResolvers.add(bsonFilterArgumentResolver);
    }
  }
```
the issue is that both class properties beans are not yet injected in the context when calling the method `addArgumentResolvers(...)`,
therefore producing an Unchecked Exception (NullPointerException) when performing calls from the Spring DispatcherServlet, during method arguments resolvers used internally by Spring.

Both Beans are declared as `@Component`, but without any explicit `@ComponentScan` declaration in your library, Spring won't create Bean Definitions and these two beans won't be present inside the ApplicationContext.
I tried adding it in one of my Configuration classes, like this: `@ComponentScan("com.turkraft.springfilter")` and doing so, the component scannig is triggered and another issue is raised: 
```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.turkraft.springfilter.boot.BsonFilterArgumentResolver] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:739)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:704)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:689)
	at org.springframework.boot.test.mock.mockito.DefinitionsParser.parse(DefinitionsParser.java:65)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:135)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:128)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:325)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:191)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:445)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 62 more
Caused by: java.lang.NoClassDefFoundError: Lorg/springframework/data/mongodb/CodecRegistryProvider;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:734)
	... 77 more
Caused by: java.lang.ClassNotFoundException: org.springframework.data.mongodb.CodecRegistryProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 81 more
```

That's a side effect due to the fact that now the configuration is not programmatic anymore. The `BsonFilterArgumentResolver` is another declared component, and during component scanning, it declares a bean that is not required (and that's fine), but the problem is that without mongo dependency in the classpath, even the bean definition fails at `PostProcessorRegistrationDelegate` class level, because the class itself might not be in the java classpath.

I'm happy to help if you need additional support/infos.

**Comment by torshid** [comment]
Hello @marcopag90, thanks for notifying about this, I am going to revert the PR for now.
